//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JustEatNavarro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        public int Id { get; set; }
        public int IdPedido { get; set; }
        public string TipoTarjeta { get; set; }
        public string NumeroTarjeta { get; set; }
        public int MesCaducidad { get; set; }
        public int AnioCaducidad { get; set; }
        public int CodigoSeguridad { get; set; }
        public System.DateTime FechaPago { get; set; }
        public string TransaccionId { get; set; }
    
        public virtual Pedido Pedido { get; set; }
    }
}
